export enum ActionType {
  FETCH_ITEMS = 'FETCH_ITEMS',
  CREATE_ITEM = 'CREATE_ITEM',
  DELETE_ITEM = 'DELETE_ITEM',
  SET_LOADING = 'SET_LOADING',
  SET_ERROR = 'SET_ERROR',
  SET_CURRENT_ID = 'SET_CURRENT_ID',
  UPDATE_ITEM = 'UPDATE_ITEM',
  UNSET_ERROR = 'UNSET_ERROR',

  AUTH = 'AUTH',
  LOGOUT = 'LOGOUT',

  SET_USER_ERROR = 'SET_USER_ERROR',
  FETCH_USER = 'FETCH_USER',
  UPDATE_USER = 'UPDATE_USER',
  UPDATE_USER_MSG = 'UPDATE_USER_MSG',
  DELETE_USER = 'DELETE_USER',
}
